name: english_project
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.6+10

environment:
  sdk: '3.0.6'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.6
  google_mobile_ads: ^3.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  restart_app: ^1.2.1
  flutter_phoenix: ^1.1.1
  freezed: ^2.4.5
  auto_route: ^6.4.0
  flutter_tts: ^3.8.3
  get_it: ^7.6.4

  freezed_annotation: ^2.4.1
  velocity_x: ^4.1.1
  reactive_forms: ^16.1.0
  font_awesome_flutter: ^10.4.0
  flutter_svg: ^2.0.0+1
  image_picker: ^0.8.5+3
  flip_card: ^0.7.0

  #view in web
  webview_flutter: ^4.4.2
  flutter_inappwebview: ^5.3.2


  #network
  html: ^0.15.4
  http: ^1.1.0
  dio: ^5.3.3
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1

  #show dialog
  material_dialogs: ^1.1.4

  #show log
  pretty_dio_logger: ^1.3.1


  #firebase
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.0
  firebase_analytics: ^10.6.2
  firebase_crashlytics: ^3.4.3

  #login at 3
  google_sign_in: ^6.1.5
  flutter_facebook_auth: ^6.0.2
  flutter_login: ^4.2.1

  #Scroll like load more
  infinite_scroll_pagination: ^4.0.0

  #translate
  #translator: ^0.1.7

  #isolate
  flutter_isolate: ^2.0.4

  #check internet
  connectivity_plus: ^5.0.1
  internet_connection_checker: ^1.0.0+1

  #change name package
  change_app_package_name: ^1.1.0

  #image
  image: ^4.1.3

  #store data
  sqflite: ^2.3.0

  #awesome_dialog
  awesome_dialog: ^3.1.0

  shared_preferences: ^2.2.2

  csv: ^5.1.1
  file_picker: ^6.1.1
  external_path: ^1.0.3

icons_launcher:
  image_path: "assets/images/logo_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  android: true
  background_image: "assets/images/splash.png"



dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.5
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.7.1
  auto_route_generator: ^6.2.0
  url_launcher: ^6.1.14





  # ads


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    #file
    - assets/file/
    #file database
    - assets/database/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
